location ^~ /api/ {
  try_files $uri $uri/ $uri.php =404;
  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
}
add_header X-HighLion "HLv8" always;
add_header X-HL-Trace "lab/briefing" always;
